language: php

php:
  - 5.4
  - 5.5
  - 5.6

compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install php5-dev
  - sudo apt-get install -qq libboost-dev
  - sudo apt-get install python-dev libevent-dev
  - sudo apt-get install libtool
before_script:
  - git clone -b noexceptions https://github.com/VoltDB/voltdb-client-cpp.git
  - cd voltdb-client-cpp
  - make
  - cd ..
  - git clone -b native https://github.com/VoltDB/voltdb-client-php.git
  - cd voltdb-client-php
  - phpize
  - ./configure --with-voltdb=../voltdb-client-cpp/
  - make
  - echo "extension=voltdb.so" > voltdb.ini && phpenv config-add voltdb.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

notifications:
  emails:
    - yuuki.takezawa@comnect.jp.net
