language: php

php:
  - 5.4
  - 5.5
  - 5.6
  
before_script:
  - sudo apt-get install ant
  - git clone https://github.com/VoltDB/voltdb.git
  - cd voltdb
  - ant 
  - cd ..
  - git clone -b noexceptions https://github.com/VoltDB/voltdb-client-cpp.git
  - cd voltdb-client-cpp
  - make
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

notifications:
  emails:
    - yuuki.takezawa@comnect.jp.net
