CREATE TABLE users (
   user_id INTEGER UNIQUE NOT NULL,
   user_name VARCHAR(40) NOT NULL,
   created_at TIMESTAMP NOT NULL
);
PARTITION TABLE users ON COLUMN user_id;

CREATE PROCEDURE addUser AS
  INSERT INTO users VALUES (?, ?, CURRENT_TIMESTAMP);

PARTITION PROCEDURE addUser ON TABLE users COLUMN user_id;

CREATE PROCEDURE getUser AS
  SELECT * FROM users WHERE user_id = ?;
PARTITION PROCEDURE getUser ON TABLE users COLUMN user_id;

CREATE PROCEDURE allUser AS SELECT * FROM users;
